import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReactQueryProviders from '@/hooks/useReactQuery'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  )
}

// import ReactQueryProviders from '@/hooks/useReactQuery'

// export default function RootLayout({ children }: React.PropsWithChildren) {
//   return (
//     <html lang="en">
//       <head />
//       <body>
//         <ReactQueryProviders>{children}</ReactQueryProviders>
//       </body>
//     </html>
//   )
// }